### ISSUE TITLE
QOS Bootstrap Tracking Issue

### ISSUE THREAD

**Issue by emostov** [tkhq/qos#29]
- [ ] Implement PowerUp through WaitingForApplication

- [ ] Update Coordinator to wait for new commands after spawning the secure application

- [ ] Implement QOS Genesis Secure app
    - [ ] Add CLI functionality for producing Genesis Ceremony Inputs per QSet Member
    - [ ] Add CLI functionality for verifying ceremony artifacts
    - [ ] Add CLI functionality for signing manifest file 
- [ ] GitHub related CLI functionality
   - [ ] Post Manifest from genesis ceremony to manifest-repo, putting the new manifest under a new nonce
   - [ ] Add commit to manifest-repo with signature of the manifest
  
- [ ] Deploy pipeline
    - [ ] Implement repo watcher that tracks the latest manifest, waits for it to get K signatures, and once it gets K signatures deploys it to production
