### ISSUE TITLE
Tracking issues for follow ups to #31

### ISSUE THREAD

**Issue by emostov** [tkhq/qos#38]
Follow up issues to #31. Some of these should be broken out into there own issues

- [x] Add attestation doc verification to boot_genesis CLI command #50 
- [x] CLI command for decrypting personal genesis outputs, and then writing them to disk as password protected values. #50 
- [ ] Comment out the entire genesis boot flow
- [x] Standard boot CLI https://github.com/tkhq/qos/pull/56
- [ ] Better documentation for the envelope encryption and add a justification for why the particular encryption strategy was used.
