### ISSUE TITLE
Provision tracking issue

### ISSUE THREAD

**Issue by emostov** [tkhq/qos#41]
- [x] provision service unit tests https://github.com/tkhq/qos/pull/44
- [x] Provision integration tests - might be dependent on having a working boot flow
- [x] CLI `provision` command that has the user decrypt their shard, encrypt the shard to the quorum public key of the given manifest, and then broadcast the provision request #56
