### ISSUE TITLE
Genesis tracking issue

### ISSUE THREAD

**Issue by emostov** [tkhq/qos#42]
- [x] Unit test for genesis service https://github.com/tkhq/qos/pull/31
- [x] Integration test for genesis https://github.com/tkhq/qos/pull/31
- [x] CLI command for running genesis https://github.com/tkhq/qos/pull/31
- [x] CLI command for generating personal key https://github.com/tkhq/qos/pull/31
- [x] CLI command for verifying genesis outputs (i.e. attestation_doc, expected PCRs), decrypting genesis member output (shard + personal key) #50 
- [ ] Fully document CLI commands and high level guide for using genesis CLI
