### ISSUE TITLE
Standard Boot tracking issue

### ISSUE THREAD

**Issue by emostov** [tkhq/qos#43]
- [x] Unit tests for boot service
- [x] Integration test for boot with CLI #56 
- [x] CLI command to generate a manifest #56
- [x] CLI command to run standard boot with a given manifest #56
- [x] CLI command to verify an attestation doc. Command should take a manifest and attestation doc as an args #56
